name: Build and Publish Gem

on:
  push:
    branches: ['*']

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install gem dependencies
        run: bundle install

      - name: Build gem
        run: rake build
